services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./Moscowregion.pkl:/app/Moscowregion.pkl
      - ./model2.h5:/app/model2.h5
    environment:
      - PYTHONUNBUFFERED=1
      - MAX_WORKERS=4
      - WORKERS_PER_CORE=1
      - TIMEOUT=120
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G  # Increased for TensorFlow
        reservations:
          cpus: '1'
          memory: 2G  # Increased for TensorFlow
